### ISSUE TITLE
GHC 7.10.2 released

### ISSUE THREAD

**Issue by dkubb** [mitchty/alpine-linux-ghc-bootstrap#1]
I'm not sure if the last bootstrapped ghc was built with the latest 7.10.2 source, but I figured I'd mention that it was released just in case: https://mail.haskell.org/pipermail/haskell/2015-July/024634.html

**Comment by mitchty** [comment]
Yep looks like the source tarball md5sum changed since 4 days ago, I'm kicking off a complete rebuild and bumping the version number for ghc/cabal-install. It takes a bit to run through the bootstrap entirely so likely won't be done for a number of hours.

When I do push things up I extract the APKBUILD files from the docker image that contain the checksum of the source files the apk is built with and check that in so its somewhat easy to compare against.

```
$ grep md5 ghc/APKBUILD 
md5sums="b6094e56e940881deb5be5d3bd5776c4  ghc-7.10.2-src.tar.bz2"
$ curl -L -o ghc-7.10.2-src.tar.bz2 "https://www.haskell.org/ghc/dist/7.10.2/ghc-7.10.2-src.tar.bz2"
$ openssl md5 ghc-7.10.2-src.tar.bz2
MD5(ghc-7.10.2-src.tar.bz2)= d4e1be9ab132f4afe9ac517c15d36fde
```

**Comment by mitchty** [comment]
Ok s3 upstream is updated with 7.10.2-r1 and cabal-install-1.22.6.0-r2 so should have things up to date with the release with things.

Docker hub image built off this is updated too, so docker pull mitchty/alpine-ghc will get this as well.

Next up: get git support working and all this jazz automated so I can have daily builds of master as well.

**Comment by dkubb** [comment]
@mitchty thanks a lot, I appreciate it.

I've been working on a simple Docker image that can be used to create Docker instances based on scratch that contain a single binary created by GHC. I've been using alpine linux and your ghc package, but I think I may just use `mitchty/alpine-ghc` as a base image, since it's 90% of what I do anyway. It's still really early but it's located at: https://github.com/dkubb/haskell-builder

**Comment by mitchty** [comment]
@dkubb cool! And yep thats the primary motivator for me porting ghc to alpine linux actually. I'm using it mostly for commandline apps however though so let me know how it works out for your purposes if they differ. So far I haven't found any issues with 7.10.2, 7.10.1 had some really odd linker issues I never tracked down, but haven't re-encountered them in 7.10.2.

As a note I'm finishing up packaging stack like I do cabal-install/ghc and will push that up into the base image probably tonightish. One nice thing about that is then don't need to pollute up the users .cabal/.ghc with stack dependencies.

If you can think of anything else to change let me know!

Should also start pestering the alpine devs to get this into base again.

**Comment by dkubb** [comment]
> As a note I'm finishing up packaging stack like I do cabal-install/ghc and will push that up into the base image probably tonightish.

Very cool. Will you be statically linking the `stack` binary? I don't think the official ones are, but I wonder if they should be to maximize portability. It would be nice if there was a single binary for all Linux systems, with the only difference being a distribution specific wrapper to ease installation further.

I wonder if there's anything standing in the way of that, or if there's some reason why it wouldn't be a good idea?

> Should also start pestering the alpine devs to get this into base again.

That would be great. As much as I appreciate your docker image, it would be better if anyone could `apk add ghc` and get your version without having to do anything special. It took me a bit of research to find out about your project, but it would be better for it to just be the default on alpine linux.

Do you think they'll accept your `cabal-install` and `stack` packages upstream too?

**Comment by mitchty** [comment]
I tried to static link it like I did cabal but got a fun linker error. Haven't researched it too hard yet. So for first release it will be dynamically linked.

As for getting this into alpine linux proper that really is the entire goal/purpose of this repo to be honest. This repo being useful for anyone that might want to port ghc/etc... to another distribution in that it has the steps from start to finish.

That and it provides me a way to test out updates/changes in isolation.

But I've been slacking off on trying to get it upstream if I'm honest. I'll redouble my efforts there this week. Its been fairly low priority since I was experiencing the weird linking errors with stack. But 7.10.2 fixed that so I don't see why all three can't get into upstream.

**Comment by dkubb** [comment]
> I tried to static link it like I did cabal but got a fun linker error.

Was it [this one](https://gist.github.com/mitchty/a697dacadab59222634f)? I ran into the same error myself earlier today and when I googled for it, your gist came up. I'm not really sure how to resolve that one.

**Comment by mitchty** [comment]
Yep thats the one. So I got it working/compiling statically. At least it seems to work. But this is a huge binary. I think for packages that alpine includes they should probably be dynamic. Its not too hard to build things statically but I don't think building stack statically makes a ton of sense for distribution packages.

But if you strip it its actually smaller than the dynamic version I just threw up into my repo. Hmm, eh, I might've just talked myself out of dynamically linked binaries.

```
bash-4.3# file dist/build/stack/stack
dist/build/stack/stack: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, not stripped
bash-4.3# du -hs !$
du -hs dist/build/stack/stack
36.9M   dist/build/stack/stack
bash-4.3# strip !$
strip dist/build/stack/stack
bash-4.3# du -hs dist/build/stack/stack
24.7M   dist/build/stack/stack
bash-4.3# du -hs /usr/bin/stack
25.4M   /usr/bin/stack
```

**Comment by dkubb** [comment]
> So I got it working/compiling statically

Oh, what did you do?

> But if you strip it its actually smaller than the dynamic version I just threw up into my repo. Hmm, eh, I might've just talked myself out of dynamically linked binaries.

lol. btw, there's a `-optl-s` switch that you can pass to ghc which will cause it to strip the resulting binary.

Also you can probably also get even tighter compression if you use [upx](http://upx.sourceforge.net/). My first attempt to get it working with alpine linux failed, but I was going to try again this week. I assume there's a small hit in terms of start-up time due to the decompression, so it may not be appropriate for your use case with command line apps. I plan to use the resulting binary/docker image to deploy apps to EC2 and Elastic Beanstalk, so transfer time to deploy is probably more important to me.

**Comment by mitchty** [comment]
> Oh, what did you do?

Basically this line:
https://github.com/mitchty/static-ghc-linux-demo/blob/master/static-demo.cabal#L19

Upx is on my list of things to port, but while it is great at shrinking executables, it does make runtimes larger. On the order of 0.01 seconds, which isn't huge by any means but unless the goal is minimizing executable size at the expense of all else it isn't the best thing from my experience. Would make more sense in your use case though. But if you could rsync as an example you probably would get no great benefit from its use. Most of the binary should be stable enough for delta transfer. With compression you'd always end up transferring it all. Worth testing though.

That and debugging a upx compressed binary is... not all that fun. I speak more from experience with c but it is a tradeoff like anything really.
