### ISSUE TITLE
integersimple variant would be neat

### ISSUE THREAD

**Issue by dysinger** [mitchty/alpine-linux-ghc-bootstrap#13]
to create static binaries w/ out GPL hangups

**Comment by mitchty** [comment]
Its only a hangup if you have to distribute >.<  

But even if gmp is lgpl I'll admit i'm no lawyer on the legality of static linking a lgpl component.

So I'm not against adding it in, but need to think how to do it within one apkbuild. Unless I can build a say ghc-integer package that includes a replaces package entry for ghc. Not sure if that can be done or not.

**Comment by mitchty** [comment]
Ok so finally have a sort of working version of this, but it means building twice which is a bit painful on arm.

It also appears to break the gmp version somehow so not sure I did it entirely right, I'll keep poking at it.

**Comment by mitchty** [comment]
Right so got it working, at least on x86_64. It produces larger binaries though, not sure if that matters, and granted I haven't tried much beyond hello world yet.

Have to clean it up a bit first though and validate it builds on arm as well. So that'll take about a day or more to validate.

```
/home/build/aports/testing/ghc # ldd /tmp/integer
        /lib/ld-musl-x86_64.so.1 (0x560402031000)
        libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x560402031000)
/home/build/aports/testing/ghc # ldd /tmp/gmp
        /lib/ld-musl-x86_64.so.1 (0x55be38018000)
        libgmp.so.10 => /usr/lib/libgmp.so.10 (0x7f8e2e81a000)
        libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x55be38018000)
/home/build/aports/testing/ghc # apk info ghc-integer
ghc-integer-8.0.2-r1 description:
The Glasgow Haskell Compiler

ghc-integer-8.0.2-r1 webpage:
http://haskell.org

ghc-integer-8.0.2-r1 installed size:
1333530624

/home/build/aports/testing/ghc # apk info ghc
ghc-8.0.2-r1 description:
The Glasgow Haskell Compiler

ghc-8.0.2-r1 webpage:
http://haskell.org

ghc-8.0.2-r1 installed size:
1255718912
```

**Comment by mitchty** [comment]
With this upstreamed now, we should likely take this to the more alpine linuxy channels. Bonus though the work is done already so its just dumping a diff of what I did and applying it to the upstreamed version.
