### ISSUE TITLE
GHC needs some PAX flags to function properly.

### ISSUE THREAD

**Issue by albertov** [mitchty/alpine-linux-ghc-bootstrap#17]
GHC sometimes trips up with PAX when compiling since (I hypothesize) it needs to JIT code. I haven't copied the exact error I got (can do if necessary) but dmesg showed something along the lines of `grsec: prevented mmap of ... by ghc ... blah blah blah). It doesn't occur always but it can be reproduced on a system running Alpine's GRSEC kernel and running "stack install yesod".

I fixed it with a big sledgehammer by adding the following lines at the end of the `package` function in GHC's APKBUILd:

``` sh
  paxctl -cpemrxs $pkgdir/usr/lib/ghc-$pkgver/bin/ghc
  paxctl -cpemrxs $pkgdir/usr/lib/ghc-$pkgver/bin/ghc-iserv
  paxctl -cpemrxs $pkgdir/usr/lib/ghc-$pkgver/bin/ghc-iserv-dyn
  paxctl -cpemrxs $pkgdir/usr/lib/ghc-$pkgver/bin/ghc-iserv-profsh
```

I'm pretty sure not all flags need to be disabled but I think at least MPROTECT (m) needs to.
I'll  reproduce and paste the logs.

**Comment by mitchty** [comment]
I suspect mprotect will probably all thats needed due to the jit, though I haven't been running alpine linux with a grsec kernel lately. Keep me apprised, I don't really use those parts of ghc so I missed checking if they needed any pax changes or not.

**Comment by mitchty** [comment]
As a note, the 8.0.2 compiler i just pushed up should have this in place. Let me know if it works! This is also what I'm trying to get upstreamed into alpine linux.

**Comment by mitchty** [comment]
Note, this is in the version now in testing. Any further changes should likely get brought up in the context of the aports repo.

http://git.alpinelinux.org/cgit/aports/commit/?id=8400dc7b515d800c1005ae28a39c444a99877ecb
