### ISSUE TITLE
The README is lying

### ISSUE THREAD

**Issue by joehillen** [mitchty/alpine-linux-ghc-bootstrap#20]
The README seems to imply that these are part of the docker image:

```
 ghc ghc-dev cabal alpine-sdk linux-headers musl-dev gmp-dev zlib-dev
```
but according to the [Dockerfile](https://hub.docker.com/r/mitchty/alpine-ghc/~/dockerfile/) only `ghc cabal stack` are installed.

Why not include them? It would be nice if all the build packages were part of the base image.

**Comment by mitchty** [comment]
The primary reason for not including them by default is people wanted the docker images to be small by default. 

I don't particularly care one way or the other but keeping it basic at the start and letting people add any sdk/dev apks seems a bit better.

And yes the readme is a bit out of date, I did a quick pass over it. Feel free to reopen, I could create an alpine-ghc:batteriesincluded docker file until this gets upstreamed into the testing repo if you like?

**Comment by mitchty** [comment]
Ref:
https://github.com/mitchty/alpine-ghc/issues/1

**Comment by mitchty** [comment]
Ok docker hub should have a new image soon: mitchty/alpine-ghc:large

Thats basically the 8.0.2 install with the header/sdk images listed in the readme. Let me know if that doesn't work/fix the need.

**Comment by joehillen** [comment]
Great idea to add `large`! Works great. Thank you.
