### ISSUE TITLE
ghc 8.0.2 unable to dcommit memory

### ISSUE THREAD

**Issue by lloucas-imvu** [mitchty/alpine-linux-ghc-bootstrap#21]
I'm seeing this error

> Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2: unable to decommit memory: Invalid argument

when using the 8.0.2 container as a base. Seems to be related to https://ghc.haskell.org/trac/ghc/ticket/12495. Not sure if theres a patch that needs to be applied to ghc 8.0.2 to fix it.

**Comment by mitchty** [comment]
Nope no patch, its actually due to the linked bug getting fixed here:
https://git.haskell.org/ghc.git/commitdiff/6576bf83cdf4eac05eb88a24aa934a736c91e3da

The issue isn't unique to the port actually, you'd see the exact same behavior if you compile ghc on a linux 4.5+ kernel or above, then build something with that and run it on a kernel < 4.5.

Ironically I do have a fix for it, aka patch the RTS to check at startup and only use MADVISE_FREE if you're running on a 4.5+ kernel. I just haven't tested it too much, I was going to test it a bit more then work on getting it upstreamed into ghc itself as I fundamentally disagree with the fix in that commit.

**Comment by mitchty** [comment]
Gah looks like 8.0.2 didn't ship with that patch, either way the same behavior would occur. Going to do a test build and build a few test programs to validate the RTS change against older kernels.

**Comment by lloucas-imvu** [comment]
Its interesting to me because the 8.0.2 container seems to be on the 4.4 kernel, and then I'm running on some older ubuntu machines on some old 3.x kernel. But it seems like the apline latest that ghc was built on was on 4.4?(unless Im mistaken)

Thanks for the prompt response!

Edit:
I tried using the one from apline:edge testing, which appears to be compiled on kernel 4.4.6 (from this log http://build.alpinelinux.org/buildlogs/build-edge-x86_64/testing/ghc/ghc-8.0.2-r0.log).
And it fails similarly.
Also, i see the following in that ghc build log.

> (3/10) Installing linux-headers (4.4.6-r2)
and 
> checking whether MADV_FREE is declared... yes
> checking whether MADV_DONTNEED is declared... yes


Thanks for the support

**Comment by lloucas-imvu** [comment]
Actually. I wonder if the version of 8.0.2 in alpine edge testing (not sure if its the exact same as the one in the container at your dockerhub) is only reporting this bug.

The build log seems to apply http://git.alpinelinux.org/cgit/aports/diff/testing/ghc/0006-fix-madvise.patch?id=8400dc7b515d800c1005ae28a39c444a99877ecb , which leads me to beleive that it will try MADV_DONTNEED after the MADV_FREE fails.

Does that seem to track?

**Comment by lloucas-imvu** [comment]
Using the port from alpine edge testing ends up working for me after I cleaned up a poisoned 8.0.2 cabal that stack had generated.

Thanks

**Comment by mitchty** [comment]
Ah cool, note even with the patch you'd still likely see the EINVAL responses from the RTS. If the RTS is compiled on a system without MADVISE_FREE no errant behavior would be seen.

What I have at the moment is simply this which puts the concern for what to use at runtime where I think it makes more sense:
https://gist.github.com/916952e00f0d6f5cc7252ffe136bd27c

I'll keep running with it and maybe apply it to the alpine linux port but I'll try to get it upstreamed as it jives much better with how I would expect things to behave.
